rule all:
    input:
        "burger_plainbun_shredded-romaine_cooked-beefpatty",
        "burger_sesamebun_shredded-iceberg_cooked-chickenbreast"

rule get_ingredient:
    output:
        "{ingredient,[a-z]+}"
    shell:
        "touch {output}"

rule shred:
    input:
        "{ingredient}"
    output:
        "shredded-{ingredient}"
    shell:
        "cp {input} {output}"

rule cook:
    input:
        "{ingredient}"
    output:
        "cooked-{ingredient}"
    shell:
        "cp {input} {output}"

rule make_burger:
    input:
        "{bun}",
        "shredded-{veggie}",
        "cooked-{patty}"
    output:
        "burger_{bun}_shredded-{veggie}_cooked-{patty}"
    shell:
        "cat {input} > {output}"

