
configfile:
    "config.yaml"

rule all:
    input:
        "burger_tray"

rule get_ingredient:
    output:
        "{ingredient,[a-z]+}"
    shell:
        "touch {output}"

rule shred:
    input:
        "{ingredient}"
    output:
        "shredded-{ingredient}"
    shell:
        "cp {input} {output}"

rule cook:
    input:
        "{ingredient}"
    output:
        "cooked-{ingredient}"
    shell:
        "cp {input} {output}"

rule make_burger:
    input:
        "{bun}",
        "shredded-{veggie}",
        "cooked-{patty}"
    output:
        "burger_{bun}_shredded-{veggie}_cooked-{patty}"
    shell:
        "cat {input} > {output}"

rule deliver_order:
    output:
        "burger_tray"
    input:
        expand("burger_{bun}_shredded-{veggie}_cooked-{patty}",
                zip,
                patty=config['patties'],
                bun=config['buns'],
                veggie=config['veggies'])
    shell:
        "cat {input} > {output}"
